//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveFreeFormatDoc
    {
        public int ArchiveFreeFormatDocID { get; set; }
        public Nullable<int> FreeFormatDocID { get; set; }
    
        public virtual FreeFormatDoc FreeFormatDoc { get; set; }
    }
}
