//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.PaymentOrders = new HashSet<PaymentOrder>();
            this.PaymentRequirements = new HashSet<PaymentRequirement>();
        }
    
        public int BankID { get; set; }
        public string Adress { get; set; }
        public Nullable<int> BanckCode { get; set; }
    
        public virtual ICollection<PaymentOrder> PaymentOrders { get; set; }
        public virtual ICollection<PaymentRequirement> PaymentRequirements { get; set; }
    }
}
