//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.UserInf = new HashSet<UserInf>();
            this.PaymentOrder = new HashSet<PaymentOrder>();
            this.PaymentRequirements = new HashSet<PaymentRequirements>();
        }
    
        public int CurrencyId { get; set; }
        public Nullable<int> Code { get; set; }
        public string CodeISO { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<double> PerOne { get; set; }
    
        public virtual ICollection<UserInf> UserInf { get; set; }
        public virtual ICollection<PaymentOrder> PaymentOrder { get; set; }
        public virtual ICollection<PaymentRequirements> PaymentRequirements { get; set; }
    }
}
