//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocStatus
    {
        public DocStatus()
        {
            this.PaymentRequirements = new HashSet<PaymentRequirements>();
            this.PaymentOrder = new HashSet<PaymentOrder>();
            this.FreeFormatDoc = new HashSet<FreeFormatDoc>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<PaymentRequirements> PaymentRequirements { get; set; }
        public virtual ICollection<PaymentOrder> PaymentOrder { get; set; }
        public virtual ICollection<FreeFormatDoc> FreeFormatDoc { get; set; }
    }
}
