//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EEBankEntities : DbContext
    {
        public EEBankEntities()
            : base("name=EEBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<DocType> DocTypes { get; set; }
        public virtual DbSet<FreeFormatDoc> FreeFormatDocs { get; set; }
        public virtual DbSet<PaymentOrder> PaymentOrders { get; set; }
        public virtual DbSet<PaymentRequirement> PaymentRequirements { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TypeOfPaymentOrder> TypeOfPaymentOrders { get; set; }
        public virtual DbSet<TypePaymentRequirement> TypePaymentRequirements { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
