//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeFormatDoc
    {
        public FreeFormatDoc()
        {
            this.ArchiveFreeFormatDoc = new HashSet<ArchiveFreeFormatDoc>();
        }
    
        public int FreeFormatDocID { get; set; }
        public Nullable<int> DocTypeID { get; set; }
        public string Document { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual DocType DocType { get; set; }
        public virtual FullInfManagers FullInfManagers { get; set; }
        public virtual Users Users { get; set; }
        public virtual DocStatus DocStatus { get; set; }
        public virtual ICollection<ArchiveFreeFormatDoc> ArchiveFreeFormatDoc { get; set; }
    }
}
