//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeFormatDoc
    {
        public int FreeFormatDocID { get; set; }
        public Nullable<int> DocTypeID { get; set; }
        public string Document { get; set; }
    
        public virtual DocType DocType { get; set; }
    }
}
