//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullInfManagers
    {
        public FullInfManagers()
        {
            this.PaymentRequirements = new HashSet<PaymentRequirements>();
            this.PaymentOrder = new HashSet<PaymentOrder>();
        }
    
        public int ManagerID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string ECP { get; set; }
        public string OpenKey { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> BankID { get; set; }
    
        public virtual Banks Banks { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<PaymentRequirements> PaymentRequirements { get; set; }
        public virtual ICollection<PaymentOrder> PaymentOrder { get; set; }
    }
}
