//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_error
    {
        public Nullable<System.DateTime> date { get; set; }
        public string user_name { get; set; }
        public string table_name { get; set; }
        public string error { get; set; }
    }
}
