//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EEBankEntitie : DbContext
    {
        public EEBankEntitie()
            : base("name=EEBankEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<DocType> DocType { get; set; }
        public virtual DbSet<FreeFormatDoc> FreeFormatDoc { get; set; }
        public virtual DbSet<PaymentOrder> PaymentOrder { get; set; }
        public virtual DbSet<PaymentRequirements> PaymentRequirements { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TypeOfPaymentOrder> TypeOfPaymentOrder { get; set; }
        public virtual DbSet<TypePaymentRequirements> TypePaymentRequirements { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserInf> UserInf { get; set; }
        public virtual DbSet<FullInfManagers> FullInfManagers { get; set; }
        public virtual DbSet<DocStatus> DocStatus { get; set; }
    }
}
