//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequirement
    {
        public int PaymentRequirementsID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TypeOfRequirements { get; set; }
        public Nullable<int> DocType { get; set; }
        public string СurrencyCode { get; set; }
        public Nullable<int> SummOfremittance { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> BankID { get; set; }
        public string Benficiar { get; set; }
        public string BankReceiver { get; set; }
        public string PaymentPurpose { get; set; }
        public Nullable<int> DocNumber { get; set; }
        public string UserUNP { get; set; }
        public string BankUNP { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual DocType DocType1 { get; set; }
        public virtual TypePaymentRequirement TypePaymentRequirement { get; set; }
        public virtual User User { get; set; }
    }
}
