//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public PaymentType()
        {
            this.PaymentOrder = new HashSet<PaymentOrder>();
        }
    
        public int PaymentTypeID { get; set; }
        public string PaymentName { get; set; }
    
        public virtual ICollection<PaymentOrder> PaymentOrder { get; set; }
    }
}
