//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentOrder
    {
        public PaymentOrder()
        {
            this.ArchivePaymentOrders = new HashSet<ArchivePaymentOrders>();
        }
    
        public int PaymentOrderID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TypeOfPaymatOrder { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> ExchangeRates { get; set; }
        public Nullable<int> UserID { get; set; }
        public string BankReceiver { get; set; }
        public Nullable<int> BankCodeID { get; set; }
        public string Benficiar { get; set; }
        public Nullable<int> BankAccount { get; set; }
        public string PaymentPurpose { get; set; }
        public string UserUNP { get; set; }
        public string ReceiverUNP { get; set; }
        public string PaymentCode { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Summ { get; set; }
    
        public virtual Banks Banks { get; set; }
        public virtual DocType DocType1 { get; set; }
        public virtual TypeOfPaymentOrder TypeOfPaymentOrder { get; set; }
        public virtual Users Users { get; set; }
        public virtual DocStatus DocStatus { get; set; }
        public virtual FullInfManagers FullInfManagers { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual ICollection<ArchivePaymentOrders> ArchivePaymentOrders { get; set; }
    }
}
