//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequirements
    {
        public PaymentRequirements()
        {
            this.ArchivePaymentRequirements = new HashSet<ArchivePaymentRequirements>();
        }
    
        public int PaymentRequirementsID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TypeOfRequirements { get; set; }
        public Nullable<int> DocType { get; set; }
        public string СurrencyCode { get; set; }
        public Nullable<int> SummOfremittance { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> BankID { get; set; }
        public string Benficiar { get; set; }
        public string BankReceiver { get; set; }
        public string PaymentPurpose { get; set; }
        public Nullable<int> DocNumber { get; set; }
        public string UserUNP { get; set; }
        public string BankUNP { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string Comment { get; set; }
    
        public virtual Banks Banks { get; set; }
        public virtual DocType DocType1 { get; set; }
        public virtual TypePaymentRequirements TypePaymentRequirements { get; set; }
        public virtual Users Users { get; set; }
        public virtual DocStatus DocStatus { get; set; }
        public virtual FullInfManagers FullInfManagers { get; set; }
        public virtual ICollection<ArchivePaymentRequirements> ArchivePaymentRequirements { get; set; }
    }
}
