//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypePaymentRequirements
    {
        public TypePaymentRequirements()
        {
            this.PaymentRequirements = new HashSet<PaymentRequirements>();
        }
    
        public int TypeId { get; set; }
        public string TypeNAme { get; set; }
    
        public virtual ICollection<PaymentRequirements> PaymentRequirements { get; set; }
    }
}
