//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfPaymentOrder
    {
        public TypeOfPaymentOrder()
        {
            this.PaymentOrder = new HashSet<PaymentOrder>();
        }
    
        public int TYpeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PaymentOrder> PaymentOrder { get; set; }
    }
}
