//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.PaymentOrder = new HashSet<PaymentOrder>();
            this.PaymentRequirements = new HashSet<PaymentRequirements>();
        }
    
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string AccountNumber { get; set; }
        public int UserId { get; set; }
        public string ECP { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<PaymentOrder> PaymentOrder { get; set; }
        public virtual ICollection<PaymentRequirements> PaymentRequirements { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
